name: Lint

on: [pull_request]

jobs:
  review:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: reviewdog/action-golangci-lint@v1
          
